[package]
name = "persil"
version = "0.1.0"
authors = ["Justus K <justus.k@protonmail.com>"]
edition = "2018"

[dependencies]
measureme = { version = "0.7.1", optional = true }
once_cell = { version = "1.4.0", optional = true }

[features]
profiler = ["measureme", "once_cell"]
